#!/bin/sh
# -*-scheme-*-

(source ../wrapper/burrow $0) && exit 0
exit 1

!#

;
; Do we have a working guile-gnome?
;

(use-modules (burrow hacks)
             (oop goops)
	     (gnome gtk))

(connect (make <gtk-window>)
	 'destroy
	 (lambda args (gtk-main-quit)))
